### ISSUE TITLE
run example turn into an error

### ISSUE THREAD

**Issue by tkhadir** [ArefMq/autonomous-vehicle#2]
![image](https://user-images.githubusercontent.com/45130488/80035340-2706dc80-84f0-11ea-9548-fc7f5f2a9137.png)

i have this error when i run the example

**Comment by ArefMq** [comment]
This is not an error, but rather it is a warning. It probably affecting your performance.
When creating a `Brain` object you could set `inner_size` to fix this.

```python
brain = Brain(inner_size=(IMAGE_WITHD, IMAGE_HEIGHT, IMAGE_CHANNELS))
```

**Comment by tkhadir** [comment]
👍good job
